### PR TITLE
640x260 is not a 16:9 resolution (reopened)

### PR DESCRIPTION
**Pull request by cameel**
**The previous pull request (#10) for the same code got closed by accident and I github won't let me reopen it so I'm just submitting a new one.**

It looks like a typo. I think it should have been 640x360.

I'd normally add a test that exposes the bug but it's hard to do so with a static definition. I use a different strategy to validate definitions and avoid simple mistakes like this in my code. I always add some assertions immediately after my definitions. For example, in this case I'd do it like this:

``` python
_resolutions = {
    "16:9": [
        [1280, 720],
        [1536, 864],
    ...
}
assert all(":" in aspect_ratio                                       for aspect_ratio, resolutions in _resolutions for resolution in resolutions)
assert all(len(resolution) == 2                                      for aspect_ratio, resolutions in _resolutions for resolution in resolutions)
assert all(aspect_ratio_matches_resolution(resolution, aspect_ratio) for aspect_ratio, resolutions in _resolutions for resolution in resolutions)
assert is_unique([resolution                                         for aspect_ratio, resolutions in _resolutions for resolution in resolutions]))
```

This may look weird to some because instead of using code at runtime to check these definitions you could just check them once and make sure they're correct, right? But in practice it works better because code is not written once and immutable - it's getting modified all the time. This approach lets you catch simple errors like this one and also expresses your assumptions in a way that lets Python enforce them on anyone modifying these definitions in the future. E.g. in the example above anyone adding a new entry will see that the aspect ratio must be a string with a ":", that resolutions are two-element lists and that these values divided by one another should give us the aspect ratio.

`aspect_ratio_matches_resolution()` would be a utility function defined elsewhere. It should deal with splitting the aspect ratio string into two ints and with the fact that the aspect ratio is not exact (e.g. that both 1366x768 and 1360x768 are acceptable approximation of 16:9 aspect ratio). Having to write this function add some programming overhead  but this is rare in my experience. Most definitions can be validated with one-liners that don't require extra definitions.

### CODE REVIEW

**Comment by nieznanysprawiciel** [comment]
I can't see this code snippet anywhere, that you are talking about. Is it some copy-paste problem ?

**Comment by cameel** [comment]
It does not look byte for byte like this in the current code. I omitted part of it for clarity because I just wanted to illustrate my point and not necessarily create a snippet that could be used as is.

The `...` part represents the long list of resolutions. And I skipped the first resolution on the list because it's the line this pull request is changing.

Anyway, these asserts are the mechanism I'm suggesting. I'm always doing it like this in my own projects. Just tell me if you like the idea. If not, well, it's just a suggestion :)

**Comment by nieznanysprawiciel** [comment]
I don't know what to think about this approach. We could try it.

**Comment by cameel** [comment]
OK. I'm not planning to start going around the code and adding it in already written code but if I see a good opportunity. we'll use it in new (or modified) code. You'll be able to see in the review and decide if you want to keep it or not.

**Pull request merged**
